ALTER TYPE quote_status ADD VALUE IF NOT EXISTS 'USED';
ALTER TYPE payout_status ADD VALUE IF NOT EXISTS 'NOT_REQUIRED';

ALTER TABLE tickets
  ADD COLUMN IF NOT EXISTS settlement_status TEXT NOT NULL DEFAULT 'PENDING',
  ALTER COLUMN payout_status SET DEFAULT 'NOT_REQUIRED';

ALTER TABLE ticket_items
  ADD COLUMN IF NOT EXISTS line_no INTEGER NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS selection_raw TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS potential_payout NUMERIC(14, 2) NOT NULL DEFAULT 0;

ALTER TABLE tickets
  ADD CONSTRAINT tickets_settlement_status_check
  CHECK (settlement_status IN ('PENDING', 'SETTLED', 'CANCELLED'));
